test_correct_login (login.login_test.loginTest) ... FAIL
test_passerr_login (login.login_test.loginTest) ... ok
test_usererr_login (login.login_test.loginTest) ... ok

======================================================================
FAIL: test_correct_login (login.login_test.loginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\私人\takin\model\modules\yancloud\login\login_test.py", line 24, in test_correct_login
    self.assertEqual(ts, text)
AssertionError: '登录成功' != '登录1成功'
- 登录成功
+ 登录1成功
?   +


----------------------------------------------------------------------
Ran 3 tests in 18.783s

FAILED (failures=1)
